# Canonical uwuAOSP source version.
# Keep the revision as an integer. Display padding is applied by consumers.
UWU_VERSION_MAJOR := 17
UWU_VERSION_QPR := 0
UWU_VERSION_REVISION := 133

ifeq ($(shell test $(UWU_VERSION_REVISION) -lt 1000 && printf true),true)
UWU_RELEASE_REVISION_DISPLAY := $(shell printf '%03d' '$(UWU_VERSION_REVISION)')
else
UWU_RELEASE_REVISION_DISPLAY := $(UWU_VERSION_REVISION)
endif

UWU_RELEASE_VERSION := $(UWU_VERSION_MAJOR).$(UWU_VERSION_QPR).$(UWU_RELEASE_REVISION_DISPLAY)

PRODUCT_VERSION_MAJOR := $(UWU_VERSION_MAJOR)
PRODUCT_VERSION_MINOR := $(UWU_VERSION_QPR)

ifeq ($(UWU_VERSION_APPEND_TIME_OF_DAY),true)
UWU_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
UWU_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

ifndef UWU_BUILDTYPE
ifdef RELEASE_TYPE
RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^UWU_||g')
UWU_BUILDTYPE := $(RELEASE_TYPE)
endif
endif

ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(UWU_BUILDTYPE)),)
UWU_BUILDTYPE := UNOFFICIAL
UWU_EXTRAVERSION :=
endif

ifeq ($(UWU_BUILDTYPE),UNOFFICIAL)
ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
UWU_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
endif
endif

UWU_VERSION_SUFFIX := $(UWU_BUILD_DATE)-$(UWU_BUILDTYPE)$(UWU_EXTRAVERSION)-$(UWU_BUILD)
UWU_VERSION := $(UWU_RELEASE_VERSION)-$(UWU_VERSION_SUFFIX)
UWU_DISPLAY_VERSION := $(UWU_VERSION)

PRODUCT_PRODUCT_PROPERTIES += \
    ro.uwu.release=$(UWU_RELEASE_VERSION) \
    ro.uwu.version=$(UWU_VERSION) \
    ro.uwu.display.version=$(UWU_DISPLAY_VERSION) \
    ro.uwu.build.version=$(UWU_RELEASE_VERSION) \
    ro.uwu.releasetype=$(UWU_BUILDTYPE) \
    ro.uwu.device=$(UWU_BUILD)

ifneq ($(strip $(UWU_MAINTAINER)),)
PRODUCT_PRODUCT_PROPERTIES += \
    ro.uwu.maintainer=$(strip $(UWU_MAINTAINER))
endif
